name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Use PNPM
        uses: pnpm/action-setup@v2.0.1
        with:
          version: ^8.9.0
          run_install: true
          install_cache: 'local'

      - name: Run Typechecks
        run: pnpm turbo typecheck --continue

      - name: Run Linting
        run: pnpm turbo lint --continue

      - name: Run Format Check
        run: pnpm turbo format --continue

      - name: Run tests
        run: pnpm test